import { clueCategories, type ClueRecord, type CountryProfile } from "./types";

const officialSources = {
  cameraGens: {
    label: "GeoHints Camera Generations",
    type: "category-reference",
    url: "https://geohints.com/meta/cameraGens",
  },
  currencies: {
    label: "GeoHints Currencies",
    type: "category-reference",
    url: "https://geohints.com/meta/currencies",
  },
  phoneNumbers: {
    label: "GeoHints Phone Numbers",
    type: "category-reference",
    url: "https://geohints.com/meta/phoneNumbers",
  },
  plonkitGuide: {
    label: "Plonk It Beginner's Guide",
    type: "official-guide",
    url: "https://www.plonkit.net/beginners-guide",
  },
  usefulResources: {
    label: "GeoHints Useful Resources",
    type: "category-reference",
    url: "https://geohints.com/meta/usefulResources",
  },
} as const;

const communityRepo = {
  label: "fabiencelier/geoguessr-tips",
  type: "community-repo",
  url: "https://github.com/fabiencelier/geoguessr-tips",
} as const;

export const countryProfiles: CountryProfile[] = [
  {
    code: "BD",
    compareCountryCodes: ["IN", "LK", "PK"],
    confusedWithCountryCodes: ["IN", "LK"],
    featuredClueIds: ["bd-google-car"],
    guideSummary:
      "Bangladesh roundlari icin arac meta ipuclari genelde ilk ayrimdir. Yol isaretleri tek basina zorlayici oldugundan kamera ve arac boyasi daha agir basar.",
    name: "Bangladesh",
    seoDescription: "Bangladesh icin Google car ve onaylayici clue kayitlarini incele.",
    strongestBeginnerClueIds: ["bd-google-car"],
  },
  {
    code: "CA",
    compareCountryCodes: ["US"],
    confusedWithCountryCodes: ["US"],
    featuredClueIds: ["ca-maximum-speed"],
    guideSummary:
      "Kanada rehberi en cok ABD ile ayrim uzerine kurulur. Ozellikle hiz tabelalarindaki kelime secimi ve metrik kullanim en hizli teyitlerden biridir.",
    name: "Canada",
    seoDescription: "Kanada tabelalari ve ABD ile karisan clue kayitlari.",
    strongestBeginnerClueIds: ["ca-maximum-speed"],
  },
  {
    code: "DE",
    compareCountryCodes: ["AT", "CH", "NL"],
    confusedWithCountryCodes: ["AT", "NL"],
    featuredClueIds: ["de-coverage-cluster"],
    guideSummary:
      "Almanya coverage paterni her yeri esit dagitmaz; buyuk sehir ve ana koridor agirligi bazi rakip Avrupa ulkelerine gore fark yaratir.",
    name: "Germany",
    seoDescription: "Almanya coverage ve kentsel yogunluk clue notlari.",
    strongestBeginnerClueIds: ["de-coverage-cluster"],
  },
  {
    code: "DK",
    compareCountryCodes: ["SE", "NO", "DE"],
    confusedWithCountryCodes: ["SE", "NO"],
    featuredClueIds: ["dk-red-warning-signs", "dk-road-lines"],
    guideSummary:
      "Danimarka icin tabela renk mantigi ve cizgi davranisi birlikte kullanildiginda diger Nordik ulkelerden ayrim hizlanir.",
    name: "Denmark",
    seoDescription: "Danimarka yol cizgileri ve kirmizi vurgulu tabela clue kayitlari.",
    strongestBeginnerClueIds: ["dk-red-warning-signs", "dk-road-lines"],
  },
  {
    code: "EE",
    compareCountryCodes: ["LV", "FI"],
    confusedWithCountryCodes: ["LV", "FI"],
    featuredClueIds: ["ee-umlauts-language"],
    guideSummary:
      "Estonya icin dil ipuclari en hizli teyitlerden biridir. Coverage ve kuzey Avrupa hissi seni Finlandiya'ya itebilir, bu nedenle alfabe farkina erken bakmak gerekir.",
    name: "Estonia",
    seoDescription: "Estonya icin dil ve alfabe tabanli clue rehberi.",
    strongestBeginnerClueIds: ["ee-umlauts-language"],
  },
  {
    code: "FI",
    compareCountryCodes: ["SE", "NO", "EE"],
    confusedWithCountryCodes: ["SE", "NO"],
    featuredClueIds: ["fi-solid-edge-lines", "fi-camera-gen"],
    guideSummary:
      "Finlandiya'da yol cizgileri ve eski-yeni kamera setleri birlikte okunur. Nordik ayrimlarda bir tek clue yerine cizgi + coverage kombinasyonu daha guvenlidir.",
    name: "Finland",
    seoDescription: "Finlandiya yol cizgileri ve kamera jenerasyonu clue kayitlari.",
    strongestBeginnerClueIds: ["fi-solid-edge-lines", "fi-camera-gen"],
  },
  {
    code: "GH",
    compareCountryCodes: ["KE", "NG", "UG"],
    confusedWithCountryCodes: ["KE", "UG"],
    featuredClueIds: ["gh-black-tape-rack", "gh-phone-code"],
    guideSummary:
      "Gana'da arac meta clue'lari birinci sinif sinyaldir. Ozellikle siyah bantli roof rack ve yerel telefon referanslari son derece ogreticidir.",
    name: "Ghana",
    seoDescription: "Gana roof rack, telefon kodu ve meta clue rehberi.",
    strongestBeginnerClueIds: ["gh-black-tape-rack", "gh-phone-code"],
  },
  {
    code: "HR",
    compareCountryCodes: ["SI", "RS", "HU"],
    confusedWithCountryCodes: ["SI", "RS"],
    featuredClueIds: ["hr-2013-camera"],
    guideSummary:
      "Hirvatistan'da kamera generasyonu tek basina bazen round'u daraltir. Ozellikle eski coverage davranisi Balkan seti icinde faydalidir.",
    name: "Croatia",
    seoDescription: "Hirvatistan kamera jenerasyonu clue kayitlari.",
    strongestBeginnerClueIds: ["hr-2013-camera"],
  },
  {
    code: "IS",
    compareCountryCodes: ["NO", "DK", "FO"],
    confusedWithCountryCodes: ["NO", "FO"],
    featuredClueIds: ["is-isk-currency", "is-phone-code", "is-bollard-secondary"],
    guideSummary:
      "Izlanda icin tek bir yol objesine baglanmak yerine dil, para birimi, telefon kodu ve ikincil yol kenari objelerini birlikte okumak daha sagliklidir.",
    name: "Iceland",
    seoDescription: "Izlanda icin para birimi, telefon kodu ve ikincil teyit clue rehberi.",
    strongestBeginnerClueIds: ["is-isk-currency", "is-phone-code"],
  },
  {
    code: "JO",
    compareCountryCodes: ["TN", "IL", "PS"],
    confusedWithCountryCodes: ["TN", "IL"],
    featuredClueIds: ["jo-coverage-limited"],
    guideSummary:
      "Jordan roundlarinda coverage yogunlugu da bir clue'dur. Tabela ve cografya kadar nerede coverage oldugunu bilmek de tahmini hizlandirir.",
    name: "Jordan",
    seoDescription: "Jordan coverage paterni ve bolgesel karisikliklar.",
    strongestBeginnerClueIds: ["jo-coverage-limited"],
  },
  {
    code: "KE",
    compareCountryCodes: ["GH", "UG", "RW"],
    confusedWithCountryCodes: ["UG", "GH"],
    featuredClueIds: ["ke-snorkel", "ke-currency"],
    guideSummary:
      "Kenya icin snorkel clue'su hala en guclu ogretim orneklerinden biridir. Arac meta sinyali goruldugunde diger dogrulayicilar sadece ikinci katmandir.",
    name: "Kenya",
    seoDescription: "Kenya snorkel ve para birimi clue rehberi.",
    strongestBeginnerClueIds: ["ke-snorkel"],
  },
  {
    code: "LV",
    compareCountryCodes: ["LT", "EE"],
    confusedWithCountryCodes: ["LT"],
    featuredClueIds: ["lv-long-a-language"],
    guideSummary:
      "Letonya ile Litvanya ayriminda dil ipuclari kritik. Benzer genel peyzaj icinde kucuk diakritik farklar buyuk deger tasir.",
    name: "Latvia",
    seoDescription: "Letonya dili ve Baltik karsilastirma clue rehberi.",
    strongestBeginnerClueIds: ["lv-long-a-language"],
  },
  {
    code: "LT",
    compareCountryCodes: ["LV", "PL"],
    confusedWithCountryCodes: ["LV", "PL"],
    featuredClueIds: ["lt-no-long-a-language"],
    guideSummary:
      "Litvanya rehberi Baltik dil ayrimini ogretir. Letonya ile karistigin roundlarda harf farki tek hamlede kilit rol oynar.",
    name: "Lithuania",
    seoDescription: "Litvanya dili ve Baltik ayrim clue notlari.",
    strongestBeginnerClueIds: ["lt-no-long-a-language"],
  },
  {
    code: "NO",
    compareCountryCodes: ["SE", "FI", "DK"],
    confusedWithCountryCodes: ["SE", "FI"],
    featuredClueIds: ["no-road-lines"],
    guideSummary:
      "Norvec icin yol cizgileri, fjord hissi kadar teknik bir teyit aracidir. Iskandinavya ayriminda cizgi mantigini aktif kullanmak gerekir.",
    name: "Norway",
    seoDescription: "Norvec yol cizgileri ve Iskandinav ayrim clue rehberi.",
    strongestBeginnerClueIds: ["no-road-lines"],
  },
  {
    code: "PT",
    compareCountryCodes: ["ES"],
    confusedWithCountryCodes: ["ES"],
    featuredClueIds: ["pt-yellow-plate"],
    guideSummary:
      "Portekiz icin plaka kenarindaki sari blok gibi kucuk objeler Iberya ayriminda cok gucludur.",
    name: "Portugal",
    seoDescription: "Portekiz plaka ve Iberya ayrim clue kayitlari.",
    strongestBeginnerClueIds: ["pt-yellow-plate"],
  },
  {
    code: "SE",
    compareCountryCodes: ["FI", "NO", "DK"],
    confusedWithCountryCodes: ["FI", "NO"],
    featuredClueIds: ["se-dashed-edge-lines", "se-bollard-secondary"],
    guideSummary:
      "Isvec rehberi cizgi ve destekleyici yol kenari objeleriyle calisir. Nordik peyzaj tek basina yeterli olmadigi icin teknik yol bilgisi one cikar.",
    name: "Sweden",
    seoDescription: "Isvec yol cizgileri ve ikincil bollard clue rehberi.",
    strongestBeginnerClueIds: ["se-dashed-edge-lines"],
  },
  {
    code: "SI",
    compareCountryCodes: ["HR", "AT", "HU"],
    confusedWithCountryCodes: ["HR", "AT"],
    featuredClueIds: ["si-road-number-km", "si-phone-code"],
    guideSummary:
      "Slovenya icin kilometre taslari ve yol numarasi kutulari cok ogretici. Kucuk objeler Balkan ve Alp gecis zonunda buyuk fark yaratir.",
    name: "Slovenia",
    seoDescription: "Slovenya kilometre tabelalari ve telefon kodu clue rehberi.",
    strongestBeginnerClueIds: ["si-road-number-km"],
  },
  {
    code: "TN",
    compareCountryCodes: ["JO", "MA"],
    confusedWithCountryCodes: ["JO", "MA"],
    featuredClueIds: ["tn-east-coast-coverage"],
    guideSummary:
      "Tunus roundlarinda coverage koseleri degerlidir. Kiyiya sikisan coverage haritasi, yalnizca saha objelerine bakmayan oyuncuyu one tasir.",
    name: "Tunisia",
    seoDescription: "Tunus coverage paterni clue kayitlari.",
    strongestBeginnerClueIds: ["tn-east-coast-coverage"],
  },
  {
    code: "TR",
    compareCountryCodes: ["RO", "BG", "GR"],
    confusedWithCountryCodes: ["RO", "BG"],
    featuredClueIds: ["tr-lira-currency"],
    guideSummary:
      "Turkiye'de para birimi ve metin gorursen teyit hizlanir. Ancak sadece alfabe degil, sayisal ve ticari gostergeler de bu rehberin parcasi olmali.",
    name: "Turkey",
    seoDescription: "Turkiye para birimi ve metin tabanli clue notlari.",
    strongestBeginnerClueIds: ["tr-lira-currency"],
  },
  {
    code: "UA",
    compareCountryCodes: ["RU", "BG", "RO"],
    confusedWithCountryCodes: ["RU"],
    featuredClueIds: ["ua-red-car"],
    guideSummary:
      "Ukrayna icin red car meta clue'su topluluk rehberlerinde cok bilinir. Ancak bunu her zaman tek hamle sinyali degil, kuvvetli bir agirlik olarak okumak gerekir.",
    name: "Ukraine",
    seoDescription: "Ukrayna red car ve benzer coverage clue rehberi.",
    strongestBeginnerClueIds: ["ua-red-car"],
  },
  {
    code: "US",
    compareCountryCodes: ["CA"],
    confusedWithCountryCodes: ["CA"],
    featuredClueIds: ["us-speed-limit"],
    guideSummary:
      "ABD ile Kanada ayriminda hiz tabelasi sozlugu oyunun en iyi baslangic derslerinden biridir. Once kelime secimine bak, sonra diger obje setlerine gec.",
    name: "United States",
    seoDescription: "ABD hiz tabelalari ve Kanada ile karsilastirmali clue notlari.",
    strongestBeginnerClueIds: ["us-speed-limit"],
  },
];

export const clueRecords: ClueRecord[] = [
  {
    beginnerFriendly: true,
    category: "google-car",
    commonConfusionCountryCodes: ["UG", "RW", "GH"],
    confidence: "high",
    countryCode: "KE",
    countryName: "Kenya",
    description:
      "Kenya'da snorkel, Google aracinin on tarafinda kadraja sarkan koyu renkli boru gibi gorunur. Tek basina her round'u kilitlemez ama goruldugunde Kenya agirligini sert sekilde arttirir.",
    distinctiveness: 5,
    id: "ke-snorkel",
    slug: "kenya-snorkel-google-car",
    sourceRefs: [communityRepo, officialSources.usefulResources],
    summary: "Gorunen snorkel Kenya lehine cok yuksek agirlik tasir.",
    tags: ["africa", "car-meta", "snorkel", "beginner"],
    title: "Snorkel ipucu",
    visualExample: {
      alt: "Street View goruntusunun sol-altinda koyu snorkel benzeri arac parcasi.",
      caption: "Kadraja giren snorkel benzeri boru, saha objesinden ziyade coverage ekipmani clue'sudur.",
    },
  },
  {
    beginnerFriendly: true,
    category: "google-car",
    commonConfusionCountryCodes: ["UG", "KE", "NG"],
    confidence: "high",
    countryCode: "GH",
    countryName: "Ghana",
    description:
      "Gana roundlarinda roof rack uzerindeki siyah bant topluluk rehberlerinde cok guclu bir meta clue olarak geciyor. Gorursen once Ghana adayini yukari cek, sonra dil ve telefon referanslariyla teyit et.",
    distinctiveness: 5,
    id: "gh-black-tape-rack",
    slug: "ghana-black-tape-rack",
    sourceRefs: [communityRepo, officialSources.usefulResources],
    summary: "Siyah bantli roof rack, Ghana icin en ogretici meta clue'lardan biri.",
    tags: ["africa", "car-meta", "roof-rack", "black-tape"],
    title: "Siyah bantli roof rack",
    visualExample: {
      alt: "Arac tavan ekipmaninda siyah bantla kapli parca.",
      caption: "Bu clue'yu tek atis yerine diger saha sinyalleriyle beraber kullanmak daha sagliklidir.",
    },
  },
  {
    beginnerFriendly: true,
    category: "google-car",
    commonConfusionCountryCodes: ["IN", "LK"],
    confidence: "high",
    countryCode: "BD",
    countryName: "Bangladesh",
    description:
      "Bangladesh coverage'i arac renk parcalariyla hatirlanir: ayna veya roof ekipmaninda kirmizi ve yesil-sari tonlari gorulebilir. Tabela ve yol hissi belirsizse arac meta clue'su erken ayrim saglar.",
    distinctiveness: 4,
    id: "bd-google-car",
    slug: "bangladesh-google-car-paint",
    sourceRefs: [communityRepo, officialSources.usefulResources],
    summary: "Bangladesh roundlarinda gorunen renkli arac parcasi kuvvetli teyittir.",
    tags: ["asia", "car-meta", "paint", "beginner"],
    title: "Renkli arac parcasi",
    visualExample: {
      alt: "Street View alt kenarinda kirmizi ve yesil tonlarinda arac parcasi.",
      caption: "Arac boyasi goruluyorsa once Bangladesh havuzunu dusun, sonra yazi ve trafik akisini kontrol et.",
    },
  },
  {
    beginnerFriendly: false,
    category: "google-car",
    commonConfusionCountryCodes: ["RU", "BG", "RO"],
    confidence: "medium",
    countryCode: "UA",
    countryName: "Ukraine",
    description:
      "Topluluk notlarinda 'red car' olarak gecen coverage izi, Ukrayna tahminlerinde agirlik tasir. Ancak bu clue tek basina guvenli degildir; yol numarasi, dil ve kentsel doku ile desteklenmelidir.",
    distinctiveness: 3,
    id: "ua-red-car",
    slug: "ukraine-red-car-meta",
    sourceRefs: [communityRepo],
    summary: "Kirmizi arac izi, Ukrayna icin orta-yuksek agirlikli meta clue'dur.",
    tags: ["europe", "car-meta", "advanced"],
    title: "Red car meta izi",
    visualExample: {
      alt: "Street View alt kenarinda kirmizi arac boyasi izi.",
      caption: "Bu clue'yu her zaman alan teyidiyle birlikte kullan.",
    },
  },
  {
    beginnerFriendly: true,
    category: "road-signs",
    commonConfusionCountryCodes: ["CA"],
    confidence: "high",
    countryCode: "US",
    countryName: "United States",
    description:
      "ABD hiz tabelalari genellikle 'Speed Limit' ifadesini yazar. Kanada'da ayni levha ailesi daha sik 'Maximum' kelimesiyle gelir; bu kelime secimi iki ulkeyi hizla ayirmak icin idealdir.",
    distinctiveness: 5,
    id: "us-speed-limit",
    slug: "us-speed-limit-wording",
    sourceRefs: [communityRepo, officialSources.usefulResources],
    summary: "'Speed Limit' sozu, Kanada yerine ABD agirligini arttirir.",
    tags: ["north-america", "signs", "speed-limit", "beginner"],
    title: "Speed Limit ifadesi",
    visualExample: {
      alt: "Beyaz siyah hiz tabelasinda Speed Limit yazisi.",
      caption: "Kelime bazli clue'lar, bayrak ezberinden daha iyi calisir.",
    },
  },
  {
    beginnerFriendly: true,
    category: "road-signs",
    commonConfusionCountryCodes: ["US"],
    confidence: "high",
    countryCode: "CA",
    countryName: "Canada",
    description:
      "Kanada hiz tabelalarinda 'Maximum' kelimesi cok ogretici bir sinyaldir. ABD'deki 'Speed Limit' kalibindan ayrildigi icin, iki ulke arasinda saniyeler kazandirir.",
    distinctiveness: 5,
    id: "ca-maximum-speed",
    slug: "canada-maximum-speed-wording",
    sourceRefs: [communityRepo, officialSources.usefulResources],
    summary: "'Maximum' ifadesi Kanada icin birinci seviye teyit clue'sudur.",
    tags: ["north-america", "signs", "speed-limit", "beginner"],
    title: "Maximum ifadesi",
    visualExample: {
      alt: "Beyaz hiz tabelasinda Maximum yazisi.",
      caption: "Metin sinyalleri benzer peyzajdaki ulkeleri ayirmada ozellikle gucludur.",
    },
  },
  {
    beginnerFriendly: true,
    category: "road-signs",
    commonConfusionCountryCodes: ["SE", "NO", "DE"],
    confidence: "medium",
    countryCode: "DK",
    countryName: "Denmark",
    description:
      "Topluluk clue notlarinda Danimarka yon ve uyari sistemlerinde kirmizi vurgu gucludur. Ozellikle beyaz zemin uzerinde kirmizi yazi veya cerceve, Nordik komsularla ayrimda yardimci olur.",
    distinctiveness: 3,
    id: "dk-red-warning-signs",
    slug: "denmark-red-sign-system",
    sourceRefs: [communityRepo, officialSources.usefulResources],
    summary: "Kirmizi vurgulu tabela dili Danimarka lehine destekleyici agirlik tasir.",
    tags: ["nordics", "signs", "red", "supporting-clue"],
    title: "Kirmizi vurgulu tabela dili",
    visualExample: {
      alt: "Beyaz zeminli ve kirmizi cerceveli yol tabelasi.",
      caption: "Tek basina yeterli degil; cizgi ve yerlesim dokusuyla birlikte oku.",
    },
  },
  {
    beginnerFriendly: false,
    category: "road-signs",
    commonConfusionCountryCodes: ["HR", "AT"],
    confidence: "high",
    countryCode: "SI",
    countryName: "Slovenia",
    description:
      "Slovenya'da kilometre veya yol referans taslarinda sari kutu icinde yol numarasi gormek cok faydalidir. Kucuk bir obje olmasina ragmen Balkan komsularindan ayrimda beklenenden daha gucludur.",
    distinctiveness: 4,
    id: "si-road-number-km",
    slug: "slovenia-road-number-km-stone",
    sourceRefs: [communityRepo, officialSources.usefulResources],
    summary: "Sari kutulu yol numarasi Slovenya icin teknik ama guclu bir teyittir.",
    tags: ["balkans", "road-markers", "advanced"],
    title: "Sari kutulu yol numarasi",
    visualExample: {
      alt: "Kucuk bir kilometre tasi uzerinde sari yol numarasi paneli.",
      caption: "Bu tip mikro clue'lar round sonu ogretimi icin idealdir.",
    },
  },
  {
    beginnerFriendly: true,
    category: "road-lines",
    commonConfusionCountryCodes: ["NO", "DK"],
    confidence: "medium",
    countryCode: "SE",
    countryName: "Sweden",
    description:
      "Isvec yol kenari cizgilerinde daha kisa kesikli ritim, Nordik ayrim notlarinda sik kullanilir. Bu clue her yolda cikmaz; ciktiginda Finlandiya ve Norvec ile karsilastirmali okunmalidir.",
    distinctiveness: 3,
    id: "se-dashed-edge-lines",
    slug: "sweden-dashed-edge-lines",
    sourceRefs: [communityRepo, officialSources.plonkitGuide],
    summary: "Kisa ritimli kesik yan cizgiler Isvec lehine destek sunar.",
    tags: ["nordics", "road-lines", "supporting-clue"],
    title: "Kesik yan cizgi ritmi",
    visualExample: {
      alt: "Yol kenarinda kisa aralikli kesik cizgi deseni.",
      caption: "Nordik ayrimda her zaman ikinci bir clue ile esle.",
    },
  },
  {
    beginnerFriendly: true,
    category: "road-lines",
    commonConfusionCountryCodes: ["SE", "NO"],
    confidence: "medium",
    countryCode: "FI",
    countryName: "Finland",
    description:
      "Finlandiya icin tam kenar cizgisi topluluk rehberlerinde one cikar. Isvec'teki daha kesik ritme karsin daha duz ve surekli kenar boyasi goruyorsan Finlandiya agirligini arttirabilirsin.",
    distinctiveness: 3,
    id: "fi-solid-edge-lines",
    slug: "finland-solid-edge-lines",
    sourceRefs: [communityRepo, officialSources.plonkitGuide],
    summary: "Daha surekli kenar cizgisi Finlandiya lehine calisir.",
    tags: ["nordics", "road-lines", "beginner"],
    title: "Surekli kenar cizgisi",
    visualExample: {
      alt: "Yol kenarinda uzun ve surekli beyaz cizgi.",
      caption: "Nordik ulkelerde yol cizgisi clue'lari tek basina degil, kombinasyon halinde kullanilmalidir.",
    },
  },
  {
    beginnerFriendly: false,
    category: "road-lines",
    commonConfusionCountryCodes: ["SE", "FI"],
    confidence: "medium",
    countryCode: "NO",
    countryName: "Norway",
    description:
      "Norvec icin daha uzun kesikler ve cizgi bosluk oranlari yardimci bir kaliptir. Fjord veya dag goruntusu seni ikna etmeden once teknik cizgi ayrimina bakmak daha savunulabilir olur.",
    distinctiveness: 3,
    id: "no-road-lines",
    slug: "norway-road-lines-pattern",
    sourceRefs: [communityRepo, officialSources.plonkitGuide],
    summary: "Kesik uzunlugu ve bosluk orani Norvec lehine destek verebilir.",
    tags: ["nordics", "road-lines", "advanced"],
    title: "Uzun kesikli cizgi paterni",
    visualExample: {
      alt: "Orta ve kenar cizgilerinde daha uzun kesik segmentler.",
      caption: "Peyzaj kadar yol muhendisligi de clue'dur.",
    },
  },
  {
    beginnerFriendly: true,
    category: "road-lines",
    commonConfusionCountryCodes: ["SE", "DE"],
    confidence: "medium",
    countryCode: "DK",
    countryName: "Denmark",
    description:
      "Danimarka'da daha kucuk ve noktasal his veren yol kenari kesikleri rehber notlarinda ayirt edici kabul edilir. Bu clue tabela diliyle beraber kullanildiginda daha anlamlidir.",
    distinctiveness: 3,
    id: "dk-road-lines",
    slug: "denmark-dotted-road-lines",
    sourceRefs: [communityRepo, officialSources.plonkitGuide],
    summary: "Noktasal kesik ritmi Danimarka ayrimina yardimci olur.",
    tags: ["nordics", "road-lines", "supporting-clue"],
    title: "Noktasal kesik ritmi",
    visualExample: {
      alt: "Kisa ve noktasal algilanan yol kenari cizgisi.",
      caption: "Bu clue'yu baska Nordik destekleyicilerle beraber kullan.",
    },
  },
  {
    beginnerFriendly: true,
    category: "license-plates",
    commonConfusionCountryCodes: ["ES"],
    confidence: "high",
    countryCode: "PT",
    countryName: "Portugal",
    description:
      "Portekiz'in eski plaka formatinda sag tarafta sari blok bulunmasi Iberya ayriminda cok guclu bir ogretim ornegidir. Gorur gormez Portekiz agirligini ciddi bicimde arttir.",
    distinctiveness: 5,
    id: "pt-yellow-plate",
    slug: "portugal-yellow-plate-strip",
    sourceRefs: [communityRepo, officialSources.usefulResources],
    summary: "Sagdaki sari plaka blogu Portekiz icin ust duzey clue'dur.",
    tags: ["iberia", "plates", "beginner"],
    title: "Sagdaki sari plaka blogu",
    visualExample: {
      alt: "Arac plakasinin saginda sari renkte dikey blok.",
      caption: "Plaka clue'lari kisa roundlarda zaman kazandirir.",
    },
  },
  {
    beginnerFriendly: false,
    category: "camera-generation",
    commonConfusionCountryCodes: ["SI", "RS", "HU"],
    confidence: "medium",
    countryCode: "HR",
    countryName: "Croatia",
    description:
      "GeoHints kamera jenerasyonu arsivi eski coverage yillarini ayirmada kullaniliyor. Hirvatistan'in eski coverage karakteri Balkan setinde taniyarak oyun sonu ogretimi icin verimli bir baslangic saglar.",
    distinctiveness: 3,
    id: "hr-2013-camera",
    slug: "croatia-older-camera-coverage",
    sourceRefs: [officialSources.cameraGens, officialSources.usefulResources],
    summary: "Eski coverage gorunumu Hirvatistan lehine teknik bir sinyal olabilir.",
    tags: ["balkans", "camera-gen", "coverage-age"],
    title: "Eski coverage karakteri",
    visualExample: {
      alt: "Daha yumusak blur ve eski Street View kamera hissi.",
      caption: "Kamera generasyonu tek basina degil, bolgesel obje setiyle birlikte okunmali.",
    },
  },
  {
    beginnerFriendly: false,
    category: "camera-generation",
    commonConfusionCountryCodes: ["SE", "EE", "NO"],
    confidence: "medium",
    countryCode: "FI",
    countryName: "Finland",
    description:
      "Finlandiya coverage'i icinde farkli kamera setleri bulunabilir. GeoHints'in kamera jenerasyonu mantigi, ayni ulke icindeki eski ve yeni coverage tonlarini tanimayip yanlis bolge cikarimi yapmani engeller.",
    distinctiveness: 2,
    id: "fi-camera-gen",
    slug: "finland-camera-generation-mix",
    sourceRefs: [officialSources.cameraGens, officialSources.usefulResources],
    summary: "Kamera jenerasyonu Finlandiya icinde bolgesel yanilgilari azaltir.",
    tags: ["nordics", "camera-gen", "advanced"],
    title: "Karismik kamera seti",
    visualExample: {
      alt: "Ayni ulkede farkli blur ve renk tonuna sahip coverage ornekleri.",
      caption: "Bu clue daha cok yanlis eleme yapmamak icin kullanilir.",
    },
  },
  {
    beginnerFriendly: true,
    category: "coverage-pattern",
    commonConfusionCountryCodes: ["TN", "IL"],
    confidence: "medium",
    countryCode: "JO",
    countryName: "Jordan",
    description:
      "Jordan coverage'i tum ulkeye homojen yayilmaz; belirli koridor ve odaklara sahiptir. Harita bilgisini ezberlemek yerine coverage bosluklarini zihinsel bir olasilik filtresi olarak kullanmak daha saglamdir.",
    distinctiveness: 3,
    id: "jo-coverage-limited",
    slug: "jordan-limited-coverage-pattern",
    sourceRefs: [communityRepo, officialSources.usefulResources],
    summary: "Coverage bosluklari Jordan tahminlerinde yardimci bir ust-katman clue'sudur.",
    tags: ["middle-east", "coverage", "strategy"],
    title: "Sinirli coverage paterni",
    visualExample: {
      alt: "Coverage noktalarinin tum ulkeye es dagilmadigini gosteren sematik dagilim.",
      caption: "Bu bilgi sahadaki objeyi degil, coverage mantigini ogretir.",
    },
  },
  {
    beginnerFriendly: true,
    category: "coverage-pattern",
    commonConfusionCountryCodes: ["JO", "MA"],
    confidence: "medium",
    countryCode: "TN",
    countryName: "Tunisia",
    description:
      "Tunus coverage'i ozellikle dogu kiyisi ve sehir yogunlugu etrafinda dusunuldugunde daha hizli daraltilir. Cografi his ile coverage mantigini birlestirmek burada verimlidir.",
    distinctiveness: 3,
    id: "tn-east-coast-coverage",
    slug: "tunisia-east-coast-coverage",
    sourceRefs: [communityRepo, officialSources.usefulResources],
    summary: "Kiyi odakli coverage mantigi Tunus icin yardimci bir filtre sunar.",
    tags: ["north-africa", "coverage", "strategy"],
    title: "Kiyi odakli coverage",
    visualExample: {
      alt: "Coverage'in kiyida yogunlastigini gosteren sematik dagilim.",
      caption: "Coverage clue'lari oyunun saf gozlem katmanina strateji ekler.",
    },
  },
  {
    beginnerFriendly: false,
    category: "coverage-pattern",
    commonConfusionCountryCodes: ["AT", "NL"],
    confidence: "low",
    countryCode: "DE",
    countryName: "Germany",
    description:
      "Almanya coverage'i buyuk sehirler ve ana koridorlarda daha bilinir hissedilebilir. Bu clue saha objesi degil, coverage yogunlugunu zihinsel onceliklendirme aracidir.",
    distinctiveness: 2,
    id: "de-coverage-cluster",
    slug: "germany-coverage-cluster",
    sourceRefs: [communityRepo, officialSources.usefulResources],
    summary: "Buyuk sehir agirligi Almanya icin zayif ama kullanisli bir ust seviye filtredir.",
    tags: ["europe", "coverage", "advanced"],
    title: "Sehir odakli coverage",
    visualExample: {
      alt: "Coverage yogunlugunun kentsel koridorlarda toplanmasini anlatan sema.",
      caption: "Bunu tek basina final clue olarak degil, on filtre olarak kullan.",
    },
  },
  {
    beginnerFriendly: true,
    category: "alphabet-language",
    commonConfusionCountryCodes: ["LT", "EE"],
    confidence: "high",
    countryCode: "LV",
    countryName: "Latvia",
    description:
      "Letonca metinde uzun a isareti 'a' uzerinde cizgiyle gorulebilir. Baltik peyzaji birbirine benzedigi icin bu kucuk diakritik farki round'u hizla kilitler.",
    distinctiveness: 5,
    id: "lv-long-a-language",
    slug: "latvia-long-a-macron",
    sourceRefs: [communityRepo, officialSources.plonkitGuide],
    summary: "a uzerindeki cizgi Letonya lehine cok guclu bir dil clue'sudur.",
    tags: ["baltics", "language", "macron", "beginner"],
    title: "Uzun a isareti",
    visualExample: {
      alt: "Tabela uzerinde a harfi ustunde cizgi bulunan Letonca kelime.",
      caption: "Dil clue'lari benzer iklimleri ayirmada en hizli katmandir.",
    },
  },
  {
    beginnerFriendly: true,
    category: "alphabet-language",
    commonConfusionCountryCodes: ["LV", "PL"],
    confidence: "high",
    countryCode: "LT",
    countryName: "Lithuania",
    description:
      "Litvanca Baltik gorunumu paylasir ama Letonca'daki uzun a isaretini tasimaz. Letonya beklediginde o diakritik cikmiyorsa Litvanya agirligini yukari cekebilirsin.",
    distinctiveness: 4,
    id: "lt-no-long-a-language",
    slug: "lithuania-no-long-a",
    sourceRefs: [communityRepo, officialSources.plonkitGuide],
    summary: "Letonca'daki uzun a isaretinin yoklugu Litvanya lehine karsilastirmali clue'dur.",
    tags: ["baltics", "language", "comparison"],
    title: "Uzun a'nin yoklugu",
    visualExample: {
      alt: "Baltik tabelada diakritik beklenen yerde sade a kullanimi.",
      caption: "Bazi clue'lar varlik kadar yoklukla da calisir.",
    },
  },
  {
    beginnerFriendly: true,
    category: "alphabet-language",
    commonConfusionCountryCodes: ["LV", "FI"],
    confidence: "high",
    countryCode: "EE",
    countryName: "Estonia",
    description:
      "Estonca'da o, u ve a ailesinden umlaut'lu harfler ve ozellikle o-tilde seti dikkat ceker. Finlandiya hissi veren roundlarda dil katmani seni dogru tarafa iter.",
    distinctiveness: 4,
    id: "ee-umlauts-language",
    slug: "estonia-umlauts-language",
    sourceRefs: [communityRepo, officialSources.plonkitGuide],
    summary: "Estonca umlaut ve o-tilde ailesi ulke ayriminda gucludur.",
    tags: ["baltics", "language", "umlaut", "beginner"],
    title: "Umlaut ve o-tilde ailesi",
    visualExample: {
      alt: "Tabela uzerinde Estoncaya ozgu umlaut ve o-tilde harfleri.",
      caption: "Yazi goruyorsan once harf ailesine bakmak cogu zaman en hizli yoldur.",
    },
  },
  {
    beginnerFriendly: true,
    category: "currency",
    commonConfusionCountryCodes: ["NO", "DK", "SE"],
    confidence: "high",
    countryCode: "IS",
    countryName: "Iceland",
    description:
      "GeoHints para birimi referansinda Izlanda icin ISK ve 'kr' kullanimi teyit katmanidir. Fiyat, banka afisi veya POS materyali goruyorsan bu bilgi saha objesinden daha guvenilir olabilir.",
    distinctiveness: 4,
    id: "is-isk-currency",
    slug: "iceland-isk-currency",
    sourceRefs: [officialSources.currencies, officialSources.plonkitGuide],
    summary: "ISK veya kr fiyat referansi Izlanda lehine kuvvetli teyit sunar.",
    tags: ["nordics", "currency", "verification"],
    title: "ISK veya kr fiyat referansi",
    visualExample: {
      alt: "Maaza veya ekran uzerinde ISK ya da kr ile yazilmis fiyat.",
      caption: "Metin tabanli ekonomik clue'lar round sonu ogreniminde cok degerlidir.",
    },
  },
  {
    beginnerFriendly: true,
    category: "domain-phone",
    commonConfusionCountryCodes: ["NO", "DK"],
    confidence: "high",
    countryCode: "IS",
    countryName: "Iceland",
    description:
      "GeoHints telefon referanslarinda Izlanda ulke kodu +354 olarak listelenir. Bir isletme tabelasinda veya arac reklaminda bunu gorursen ulke teyidi icin cok guclu bir metin clue'su yakalamissin demektir.",
    distinctiveness: 5,
    id: "is-phone-code",
    slug: "iceland-phone-code-354",
    sourceRefs: [officialSources.phoneNumbers, officialSources.plonkitGuide],
    summary: "+354 telefon kodu Izlanda icin ust duzey teyit clue'sudur.",
    tags: ["nordics", "phone", "beginner", "verification"],
    title: "+354 telefon kodu",
    visualExample: {
      alt: "Tabela ya da reklam uzerinde +354 ile baslayan telefon numarasi.",
      caption: "Telefon kodlari, dil veya peyzaj kararsizken net kilit vurur.",
    },
  },
  {
    beginnerFriendly: false,
    category: "bollards",
    commonConfusionCountryCodes: ["NO", "SE", "FI"],
    confidence: "low",
    countryCode: "IS",
    countryName: "Iceland",
    description:
      "GeoHints bollard arsivi, Izlanda'yi diger Avrupa ulkeleriyle gorusel olarak karsilastirma mantigi sunar. Uygulamada bu kayit ikincil teyit olarak tutulur: reflector yerlesimi ve govde hissi benzerse Izlanda ihtimali artar, ama tek basina final karar verilmez.",
    distinctiveness: 2,
    id: "is-bollard-secondary",
    slug: "iceland-bollard-secondary-confirm",
    sourceRefs: [officialSources.usefulResources],
    summary: "Izlanda bollard eslesmesi ikincil teyit olarak kullanilmalidir.",
    tags: ["nordics", "bollards", "secondary-confirm", "advanced"],
    title: "Bollard ile ikincil teyit",
    visualExample: {
      alt: "Yol kenarinda reflector yerlesimi dikkat ceken Avrupa tipi bollard.",
      caption: "Bollard clue'lari en iyi karsilastirmali library ile ogrenilir.",
    },
  },
  {
    beginnerFriendly: false,
    category: "bollards",
    commonConfusionCountryCodes: ["NO", "FI"],
    confidence: "low",
    countryCode: "SE",
    countryName: "Sweden",
    description:
      "GeoHints siniflandirma mantigina gore bollard'lar tek cizgilik bir kuraldan cok library eslestirmesi gerektirir. Isvec bollard'i bu veritabaninda destekleyici clue olarak konumlandirilir ve her zaman cizgi ipuclariyla birlikte sunulur.",
    distinctiveness: 2,
    id: "se-bollard-secondary",
    slug: "sweden-bollard-secondary-confirm",
    sourceRefs: [officialSources.usefulResources],
    summary: "Isvec bollard clue'su library tabanli ve ikincil agirlikli kullanilir.",
    tags: ["nordics", "bollards", "secondary-confirm"],
    title: "Library tabanli bollard teyidi",
    visualExample: {
      alt: "Isvec ile bagdastirilabilen reflector yerlesimine sahip yol kenari bollard'i.",
      caption: "Bu kategori en iyi ekran goruntusu arsiviyle zenginlestirilir.",
    },
  },
  {
    beginnerFriendly: true,
    category: "domain-phone",
    commonConfusionCountryCodes: ["AT", "HR", "HU"],
    confidence: "high",
    countryCode: "SI",
    countryName: "Slovenia",
    description:
      "GeoHints telefon listesine gore +386, Slovenya teyidinde cok degerli bir metin clue'sudur. Balkan ve Orta Avrupa gecis zonunda bu tip sayisal referanslar tahmini aninda kapatir.",
    distinctiveness: 5,
    id: "si-phone-code",
    slug: "slovenia-phone-code-386",
    sourceRefs: [officialSources.phoneNumbers, officialSources.plonkitGuide],
    summary: "+386, Slovenya icin yuksek guvenli telefon clue'sudur.",
    tags: ["balkans", "phone", "verification"],
    title: "+386 telefon kodu",
    visualExample: {
      alt: "Acilis kodu +386 olan isletme telefon numarasi.",
      caption: "Telefon kodu, mikro yol objesi gormediginde bile round'u kapatabilir.",
    },
  },
  {
    beginnerFriendly: true,
    category: "domain-phone",
    commonConfusionCountryCodes: ["NG", "UG", "KE"],
    confidence: "high",
    countryCode: "GH",
    countryName: "Ghana",
    description:
      "GeoHints telefon kaynaklarinda Gana'nin +233 kodu listelenir. Siyah bantli roof rack ile birlikte +233 gormek, round sonu egitim kartinda cok guclu iki katmanli hikaye kurar.",
    distinctiveness: 5,
    id: "gh-phone-code",
    slug: "ghana-phone-code-233",
    sourceRefs: [officialSources.phoneNumbers, officialSources.usefulResources],
    summary: "+233, Ghana roof rack clue'sunu dogrulayan net bir metin sinyalidir.",
    tags: ["africa", "phone", "verification"],
    title: "+233 telefon kodu",
    visualExample: {
      alt: "Tabela uzerinde +233 ile baslayan telefon numarasi.",
      caption: "Meta clue + metin teyidi birlikte gelirse guven seviyesi artar.",
    },
  },
  {
    beginnerFriendly: true,
    category: "currency",
    commonConfusionCountryCodes: ["UG", "TZ"],
    confidence: "medium",
    countryCode: "KE",
    countryName: "Kenya",
    description:
      "Para birimi gorulen roundlarda KSh veya Kenya shilling referansi, snorkel gibi coverage clue'larini metinle sabitlemeye yardim eder. Ozellikle pazar, banka veya market cevresinde etkilidir.",
    distinctiveness: 3,
    id: "ke-currency",
    slug: "kenya-currency-ksh",
    sourceRefs: [officialSources.currencies, officialSources.usefulResources],
    summary: "KSh referansi Kenya tahminine metin tabanli destek verir.",
    tags: ["africa", "currency", "verification"],
    title: "KSh veya Kenya shilling referansi",
    visualExample: {
      alt: "Fiyat etiketinde KSh kisaltmasi.",
      caption: "Para birimi clue'lari meta clue'lari dogrulamak icin idealdir.",
    },
  },
  {
    beginnerFriendly: true,
    category: "currency",
    commonConfusionCountryCodes: ["BG", "RO", "AZ"],
    confidence: "medium",
    countryCode: "TR",
    countryName: "Turkey",
    description:
      "Turk lirasinin sembolu veya TL kisaltmasi gorulen roundlarda ulke teyidi hizlanir. Yaziyi okuyabildigin durumlarda trafik, mimari ve yol dokusundan daha direkt bir bilgi verir.",
    distinctiveness: 4,
    id: "tr-lira-currency",
    slug: "turkey-lira-currency",
    sourceRefs: [officialSources.currencies],
    summary: "TL veya lira referansi Turkiye icin guclu ticari teyittir.",
    tags: ["middle-east", "europe", "currency", "verification"],
    title: "TL veya lira referansi",
    visualExample: {
      alt: "Magaza veya reklam panosunda TL ile yazilmis fiyat.",
      caption: "Metin goruyorsan bunu once sayisal teyide cevir.",
    },
  },
];

export const clueCategoryMeta = clueCategories;
