import type { GameLocationRecord, GameLocationWithClues, LocationClueRecord } from "./types";

type SeedLocationInput = Omit<GameLocationRecord, "id" | "slug"> & {
  clueSeed: Omit<LocationClueRecord, "id" | "locationId">[];
  key: string;
};

const curatedSeedInput: SeedLocationInput[] = [
  {
    clueSeed: [
      {
        category: "language",
        confidence: "high",
        details:
          "Bu kayitta dukkân tabelalari, otomatlar ya da park uyarilarinda kana ve kanji karmasi aranir. Latin yazidan cok daha sikisik ve kutu gibi dizilen karakterler Tokyo icin guclu bir sinyal verir.",
        distinctiveness: 5,
        positionHint: "dukkan cepheleri ve pano yazilari",
        shortText: "Kana ve kanji karisimi tabelalar ara.",
        sortOrder: 10,
        tags: ["script", "tokyo", "signage"],
        timing: "revealed",
        title: "Japonca yazi sistemi",
      },
      {
        category: "street-furniture",
        confidence: "high",
        details:
          "Dar mahalle sokaklarinda kose aynalari ve cok yogun havai kablo goruntusu bu sahnede belirleyici olmalidir. Japon yerlesim dokusunda elektrik direkleri kadraji hizla doldurur.",
        distinctiveness: 4,
        positionHint: "kavsak kosesi ve ust hat",
        shortText: "Kose aynasi ve yogun havai kablo taramasi yap.",
        sortOrder: 20,
        tags: ["utility-poles", "mirror", "residential"],
        timing: "playing",
        title: "Mahalle altyapisi",
      },
      {
        category: "road-layout",
        confidence: "medium",
        details:
          "Cok dar seritler, yumusak virajlar ve bina cephesine neredeyse surten yol kesiti Tokyo mahallelerinde sik gorulur. Bu kurgu Japonya tahminini destekler.",
        distinctiveness: 3,
        positionHint: "yol genisligi",
        shortText: "Sokak olcegi beklenenden daha dar.",
        sortOrder: 30,
        tags: ["lane-width", "urban"],
        timing: "revealed",
        title: "Dar sokak kesiti",
      },
      {
        category: "architecture",
        confidence: "medium",
        details:
          "Dusuk katli, birbirine yakin evler; kepenkli girisler ve ince balkon detaylari kentsel Japon mahalle hissini kuvvetlendirir.",
        distinctiveness: 3,
        positionHint: "cepheler",
        shortText: "Dusuk katli yakin parselleri incele.",
        sortOrder: 40,
        tags: ["housing", "dense-neighborhood"],
        timing: "playing",
        title: "Sik parsel dokusu",
      },
      {
        category: "vehicles",
        confidence: "medium",
        details:
          "Park eden araclarda kompakt kasa orani yuksek olur; levha formati ve dar sokakla birlikte dusunuldugunde Japonya lehine calisir.",
        distinctiveness: 2,
        positionHint: "park halindeki araclar",
        shortText: "Kompakt arac yogunluguna dikkat et.",
        sortOrder: 50,
        tags: ["cars", "plates"],
        timing: "revealed",
        title: "Kompakt arac profili",
      },
    ],
    context: {
      countryCode: "JP",
      countryName: "Japonya",
      locality: "Tokyo",
      regionName: "Taito / Yanaka cevresi",
    },
    difficulty: "easy",
    heading: 84,
    key: "tokyo-yanaka",
    label: "Tokyo mahalle dokusu",
    pitch: -2,
    position: { lat: 35.7257, lng: 139.7686 },
    status: "ready",
    summary:
      "Sikisik kentsel doku, Japonca yazi sistemi ve yogun havai kablo kombinasyonu uzerinden okunacak bir Tokyo mahallesi.",
    tags: ["asia", "urban", "japan", "script-heavy"],
    verificationNotes:
      "Starter kayit. Pano bazli audit yapildiginda ayni sahne icin plaka ve levha ornekleri daha da sertlestirilebilir.",
    verificationState: "seeded",
    viewZoom: 1,
  },
  {
    clueSeed: [
      {
        category: "language",
        confidence: "high",
        details:
          "Thai alfabesi yogun ve yuvarlak karakter bloklariyla hemen ayrisir. Bu kayitta is yeri tabelalari ya da duvar yazilarinda Latin yerine Thai karakterleri aranir.",
        distinctiveness: 5,
        positionHint: "dukkan tabelalari",
        shortText: "Yuvarlak Thai karakterlerini ara.",
        sortOrder: 10,
        tags: ["thai-script", "signage"],
        timing: "revealed",
        title: "Thai yazi sistemi",
      },
      {
        category: "street-furniture",
        confidence: "high",
        details:
          "Bangkok sokaklarinda kablo yogunlugu cok yuksek olabilir. Sahnedeki kalin kablo demetleri ve direkler bolgesel ipucunu guclendirir.",
        distinctiveness: 4,
        positionHint: "ust hatlar",
        shortText: "Direk ustunde yigilmis kablolari tara.",
        sortOrder: 20,
        tags: ["overhead-wires", "tropical-city"],
        timing: "playing",
        title: "Asili kablo yogunlugu",
      },
      {
        category: "road-layout",
        confidence: "medium",
        details:
          "Dar ama hareketli kent ici yol, duz cephenin hemen yaninda motosiklet ve tuketim odakli vitrinlerle birlikte Bangkok hissini verir.",
        distinctiveness: 3,
        positionHint: "yol ve kaldirim iliskisi",
        shortText: "Dar yol ile yogun ticaret bir arada.",
        sortOrder: 30,
        tags: ["dense-urban", "southeast-asia"],
        timing: "playing",
        title: "Ticaret sokagi ritmi",
      },
      {
        category: "vehicles",
        confidence: "medium",
        details:
          "Motosiklet yogunlugu ve cadde kenarinda toplu park aliskanligi bu lokasyonda Tayland lehine calisan ikincil sinyaldir.",
        distinctiveness: 3,
        positionHint: "yol kenari park",
        shortText: "Motosiklet yogunluguna bak.",
        sortOrder: 40,
        tags: ["motorbikes", "parking"],
        timing: "revealed",
        title: "Motosiklet profili",
      },
      {
        category: "architecture",
        confidence: "medium",
        details:
          "Metal kepenkler, golgelik brandalar ve sokaga yakin ticari cepheler tropik Asya merkezlerinde guclu bir kombinasyondur.",
        distinctiveness: 2,
        positionHint: "cepheler ve brandalar",
        shortText: "Kepenk ve branda yogunlugunu incele.",
        sortOrder: 50,
        tags: ["storefront", "awnings"],
        timing: "revealed",
        title: "Sokaga tasan ticari cephe",
      },
    ],
    context: {
      countryCode: "TH",
      countryName: "Tayland",
      locality: "Bangkok",
      regionName: "Eski merkez cevresi",
    },
    difficulty: "easy",
    heading: 112,
    key: "bangkok-old-town",
    label: "Bangkok ticari sokagi",
    pitch: -1,
    position: { lat: 13.7515, lng: 100.5012 },
    status: "ready",
    summary:
      "Thai yazisi, kablo yogunlugu ve motosiklet profiliyle ayristirilacak yogun bir Bangkok cephesi.",
    tags: ["asia", "urban", "thailand", "script-heavy"],
    verificationNotes:
      "Starter kayit. Sonraki audit turunda tabela crop'lari ve sag-sol trafik ayraclari eklenebilir.",
    verificationState: "seeded",
    viewZoom: 1,
  },
  {
    clueSeed: [
      {
        category: "language",
        confidence: "high",
        details:
          "Yunan alfabesi Latin'den ayri okunur; sigma, omega ve theta gibi karakterler sokak tabelalarinda ayirt edici olur. Bu kayitta ana belirleyici ipucu yazidir.",
        distinctiveness: 5,
        positionHint: "sokak tabelalari ve isyeri yazilari",
        shortText: "Yunan alfabesini yakala.",
        sortOrder: 10,
        tags: ["greek-script", "alphabet"],
        timing: "revealed",
        title: "Yunan alfabesi",
      },
      {
        category: "architecture",
        confidence: "medium",
        details:
          "Acil renkli binalardan cok krem ve beyaz tonlu apartman cepheleri, dar balkonlar ve Akdeniz isi ile parlayan duvarlar gorulmesi beklenir.",
        distinctiveness: 3,
        positionHint: "apartman cepheleri",
        shortText: "Acik renkli balkonlu apartman dizilimine bak.",
        sortOrder: 20,
        tags: ["balconies", "mediterranean"],
        timing: "playing",
        title: "Akdeniz apartman cephesi",
      },
      {
        category: "road-layout",
        confidence: "medium",
        details:
          "Yurume yogunlugu olan merkez sokakta kaldirim ve bina cephesi birbirine yakindir. Dar merkez doku Atina icin makul bir arka plandir.",
        distinctiveness: 2,
        positionHint: "sokak profili",
        shortText: "Merkez doku dar ve yaya odakli.",
        sortOrder: 30,
        tags: ["downtown", "walkable"],
        timing: "playing",
        title: "Yaya odakli merkez doku",
      },
      {
        category: "street-furniture",
        confidence: "medium",
        details:
          "Mavi belediye tabelalari, ince yon levhalari ve cepheye yakin trafik isaretleri Yunanca yaziyla birlikte guclu bir kombinasyon yaratir.",
        distinctiveness: 3,
        positionHint: "levhalar",
        shortText: "Mavi yerel levha tipine dikkat et.",
        sortOrder: 40,
        tags: ["signage", "municipal"],
        timing: "revealed",
        title: "Yerel levha dili",
      },
      {
        category: "environment",
        confidence: "low",
        details:
          "Kuru isik, parlak gunes ve acik tonlu yuzeyler tek basina yeterli degildir ama Yunan yazisi ve balkonlu cephelerle birlestiginde Atina lehine calisir.",
        distinctiveness: 2,
        positionHint: "isik ve ortam",
        shortText: "Kuru Akdeniz isigi ikincil bir teyit saglar.",
        sortOrder: 50,
        tags: ["light", "climate"],
        timing: "revealed",
        title: "Akdeniz isigi",
      },
    ],
    context: {
      countryCode: "GR",
      countryName: "Yunanistan",
      locality: "Atina",
      regionName: "Plaka / merkez cevresi",
    },
    difficulty: "medium",
    heading: 148,
    key: "athens-plaka",
    label: "Atina merkez sokagi",
    pitch: -1,
    position: { lat: 37.9734, lng: 23.7297 },
    status: "ready",
    summary:
      "Yunan alfabesi ve Akdeniz apartman dokusuyla ayristirilan bir Atina merkez sahnesi.",
    tags: ["europe", "greece", "urban", "script-heavy"],
    verificationNotes:
      "Starter kayit. Audit sonrasi spesifik sokak tabelasi renkleri ve plaka gorunurlugu sertlestirilebilir.",
    verificationState: "seeded",
    viewZoom: 1,
  },
  {
    clueSeed: [
      {
        category: "language",
        confidence: "high",
        details:
          "Hangul blok yapiya sahip karakterleriyle hemen ayrilir. Bu sahnede market, kafe veya yonlendirme tabelalarinda Hangul aramak ilk dogru hamledir.",
        distinctiveness: 5,
        positionHint: "dukan ve sokak yazilari",
        shortText: "Hangul blok karakterlerini tara.",
        sortOrder: 10,
        tags: ["hangul", "signage"],
        timing: "revealed",
        title: "Hangul tabelalar",
      },
      {
        category: "road-layout",
        confidence: "medium",
        details:
          "Eğimli dar sokaklar ve duz olmayan kentsel profil Seoul merkezinin eski mahallelerinde sik karsilanir.",
        distinctiveness: 3,
        positionHint: "eğim ve yol profili",
        shortText: "Sokakta yukseklik farki var mi bak.",
        sortOrder: 20,
        tags: ["hillside", "old-neighborhood"],
        timing: "playing",
        title: "Eğimli mahalle sokagi",
      },
      {
        category: "street-furniture",
        confidence: "medium",
        details:
          "Direkler, kamera kutulari ve duvar ustu teknik ekipman Kore sehir dokusunda yogun hissedilir. Bu sahnede modern kent altyapisi eski dokuya yapisiktir.",
        distinctiveness: 3,
        positionHint: "direk ve kutular",
        shortText: "Modern teknik ekipman yogunlugunu kontrol et.",
        sortOrder: 30,
        tags: ["infrastructure", "cameras"],
        timing: "playing",
        title: "Teknik altyapi yogunlugu",
      },
      {
        category: "architecture",
        confidence: "medium",
        details:
          "Alcak ve orta katli karmasik binalar, tavan arasi eklentileri ve yogun cephe degisikligi Seoul mahalle hissini destekler.",
        distinctiveness: 2,
        positionHint: "cepheler ve cati cizgisi",
        shortText: "Bina yukseklikleri ve cephe farklarini oku.",
        sortOrder: 40,
        tags: ["mixed-buildings", "urban"],
        timing: "revealed",
        title: "Katmanli kentsel doku",
      },
      {
        category: "vehicles",
        confidence: "medium",
        details:
          "Park eden beyaz ve gri araclar, levha bicimi ve Hangul ile birlikte dusunuldugunde Guney Kore secenegini guclendirir.",
        distinctiveness: 2,
        positionHint: "parkli araclar",
        shortText: "Levha bicimiyle birlikte arac park profiline bak.",
        sortOrder: 50,
        tags: ["cars", "plates"],
        timing: "revealed",
        title: "Kore kentsel arac profili",
      },
    ],
    context: {
      countryCode: "KR",
      countryName: "Guney Kore",
      locality: "Seul",
      regionName: "Jongno / Bukchon cevresi",
    },
    difficulty: "medium",
    heading: 35,
    key: "seoul-bukchon",
    label: "Seul yamaç mahallesi",
    pitch: -1,
    position: { lat: 37.5826, lng: 126.9831 },
    status: "ready",
    summary:
      "Hangul yazisi ve egimli mahalle dokusuyla okunacak bir Seoul eski merkez kaydi.",
    tags: ["asia", "korea", "urban", "script-heavy"],
    verificationNotes:
      "Starter kayit. Audit turlarinda cizgi, levha ve otobus duragi detaylari sertlestirilecek.",
    verificationState: "seeded",
    viewZoom: 1,
  },
  {
    clueSeed: [
      {
        category: "language",
        confidence: "high",
        details:
          "Ibranice karakterler Latin ve Arap harflerinden ayri gorunur. Bu lokasyonda tabelalarda veya cephe panolarinda Ibranice aranmasi gerekir.",
        distinctiveness: 5,
        positionHint: "dukkan ve yonlendirme tabelalari",
        shortText: "Ibranice yaziyi yakala.",
        sortOrder: 10,
        tags: ["hebrew", "signage"],
        timing: "revealed",
        title: "Ibranice yazi sistemi",
      },
      {
        category: "environment",
        confidence: "medium",
        details:
          "Parlak isik, acik renk cepheler ve kurak-ilik Akdeniz atmosferi sahneyi Israil lehine iter; ama asıl ayirici yine yazidir.",
        distinctiveness: 2,
        positionHint: "isik ve bitki dokusu",
        shortText: "Akdeniz isigi ve acik tonlu cepheyi not et.",
        sortOrder: 20,
        tags: ["mediterranean", "light"],
        timing: "playing",
        title: "Akdeniz ortam hissi",
      },
      {
        category: "vehicles",
        confidence: "medium",
        details:
          "Israil'de sari plaka rengi guclu teyit aracidir. Bu kayitta park eden araclar gorunurse plaka rengi kontrol edilmelidir.",
        distinctiveness: 4,
        positionHint: "parkli araclar",
        shortText: "Sari plaka gorunurse kuvvetli teyit alirsin.",
        sortOrder: 30,
        tags: ["plates", "yellow-plates"],
        timing: "revealed",
        title: "Sari plaka teyidi",
      },
      {
        category: "architecture",
        confidence: "medium",
        details:
          "Dusuk-orta katli acik renkli bloklar, duz cepheler ve sicak iklime uyumlu pencere golgelikleri sahnenin Tel Aviv cevresi olmasini destekler.",
        distinctiveness: 3,
        positionHint: "bina cepheleri",
        shortText: "Acik tonlu sicak iklim cephelerine bak.",
        sortOrder: 40,
        tags: ["facades", "urban"],
        timing: "playing",
        title: "Sicak iklim cephesi",
      },
      {
        category: "street-furniture",
        confidence: "low",
        details:
          "Yerel yon levhalari ve teknik kutular Ibranice ile birlestiginde kuvvetlenir; tek basina yeterli degildir.",
        distinctiveness: 2,
        positionHint: "kaldirim ekipmanlari",
        shortText: "Levha ve teknik kutulari yaziyla beraber degerlendir.",
        sortOrder: 50,
        tags: ["street-equipment", "wayfinding"],
        timing: "revealed",
        title: "Yerel sokak ekipmani",
      },
    ],
    context: {
      countryCode: "IL",
      countryName: "Israil",
      locality: "Tel Aviv",
      regionName: "Merkez mahalle cevresi",
    },
    difficulty: "medium",
    heading: 205,
    key: "tel-aviv-center",
    label: "Tel Aviv merkez doku",
    pitch: -1,
    position: { lat: 32.0618, lng: 34.7707 },
    status: "ready",
    summary:
      "Ibranice yazi, sari plaka teyidi ve sicak Akdeniz kentsel atmosferiyle ayristirilan Tel Aviv kaydi.",
    tags: ["middle-east", "israel", "urban", "script-heavy"],
    verificationNotes:
      "Starter kayit. Audit sonrasi yerel levha tipleri ve kaldirim mobilyasi detaylari guclendirilecek.",
    verificationState: "seeded",
    viewZoom: 1,
  },
  {
    clueSeed: [
      {
        category: "language",
        confidence: "high",
        details:
          "Gurcu alfabesi yuvarlak ve akiskan karakter formuyla ayri okunur. Latin ya da Kiril olmayan bu yaziyi tespit etmek lokasyonu hizla daraltir.",
        distinctiveness: 5,
        positionHint: "dukkan tabelalari",
        shortText: "Gurcu alfabesini tespit et.",
        sortOrder: 10,
        tags: ["georgian-script", "signage"],
        timing: "revealed",
        title: "Gurcu yazi sistemi",
      },
      {
        category: "road-layout",
        confidence: "medium",
        details:
          "Eski Tiflis cevresinde sokaklar egimli olabilir ve bina cephesi yola cok yakindir. Kadrajda yukseklik farki guclu bir ikincil ipucudur.",
        distinctiveness: 3,
        positionHint: "yol egimi",
        shortText: "Yukseklik farkini ve dar sokagi incele.",
        sortOrder: 20,
        tags: ["slope", "old-town"],
        timing: "playing",
        title: "Eğimli eski kent sokagi",
      },
      {
        category: "architecture",
        confidence: "medium",
        details:
          "Tiflis'te ahsap balkonlu ya da cikmali cepheler, eski ile yeni yapinin birbirine girmesiyle fark edilir. Bu karisim kaydi ayirt eder.",
        distinctiveness: 4,
        positionHint: "balkon ve cikmalar",
        shortText: "Cikmali eski cepheleri ara.",
        sortOrder: 30,
        tags: ["balconies", "historic-core"],
        timing: "revealed",
        title: "Eski Tiflis balkon dili",
      },
      {
        category: "street-furniture",
        confidence: "low",
        details:
          "Karma park duzeni, duvara yakin direkler ve yamac mahalle altyapisi yaziyla birlestiginde Tiflis lehine calisir.",
        distinctiveness: 2,
        positionHint: "park ve direkler",
        shortText: "Yamac mahalle altyapisini yaziyla birlestir.",
        sortOrder: 40,
        tags: ["parking", "utility"],
        timing: "playing",
        title: "Yamac altyapi karmasi",
      },
      {
        category: "environment",
        confidence: "low",
        details:
          "Kuru ic-kafkas isi ve sokak topografyasi tek basina yeterli degil ama Gurcu alfabesi ile guclu bir paket olusturur.",
        distinctiveness: 2,
        positionHint: "genel ortam",
        shortText: "Topografya ve yaziyi birlikte oku.",
        sortOrder: 50,
        tags: ["topography", "climate"],
        timing: "revealed",
        title: "Topografik teyit",
      },
    ],
    context: {
      countryCode: "GE",
      countryName: "Gurcistan",
      locality: "Tiflis",
      regionName: "Eski sehir cevresi",
    },
    difficulty: "hard",
    heading: 164,
    key: "tbilisi-old-town",
    label: "Tiflis eski sehir",
    pitch: -2,
    position: { lat: 41.6913, lng: 44.808 },
    status: "ready",
    summary:
      "Gurcu alfabesi ve yamaç doku karisimi sayesinde ayristirilan bir Tiflis eski sehir kaydi.",
    tags: ["caucasus", "georgia", "historic", "script-heavy"],
    verificationNotes:
      "Starter kayit. Audit sonrasi balkon tipi ve levha tipleriyle daha spesifik hale getirilecek.",
    verificationState: "seeded",
    viewZoom: 1,
  },
  {
    clueSeed: [
      {
        category: "language",
        confidence: "high",
        details:
          "Kiril karakterler Latin ile karisabilir ama Bulgarca yol ve isyeri yazilarinda fark edilir. Bu sahnede yaziyi yakalamak temel hamledir.",
        distinctiveness: 4,
        positionHint: "sokak tabelalari",
        shortText: "Kiril yaziyi Latin'den ayir.",
        sortOrder: 10,
        tags: ["cyrillic", "signage"],
        timing: "revealed",
        title: "Kiril yazisi",
      },
      {
        category: "architecture",
        confidence: "medium",
        details:
          "Sosyalist donem ve daha yeni cephelerin karmasi, orta-yuksek apartman bloklari ve merkez sokak hissi Sofya icin tutarli bir arka plan verebilir.",
        distinctiveness: 3,
        positionHint: "blok cepheler",
        shortText: "Blok apartman karmasina dikkat et.",
        sortOrder: 20,
        tags: ["apartments", "eastern-europe"],
        timing: "playing",
        title: "Dogu Avrupa blok dili",
      },
      {
        category: "street-furniture",
        confidence: "medium",
        details:
          "Tramvay, tel hattı, direkler veya merkez kentsel ekipmanlar Kiril yaziyla birlestiginde Sofya merkez secenegini kuvvetlendirir.",
        distinctiveness: 3,
        positionHint: "ust hat ve merkez ekipmani",
        shortText: "Merkez ekipmanini yaziyla birlikte oku.",
        sortOrder: 30,
        tags: ["tram", "utility"],
        timing: "playing",
        title: "Merkez altyapi izi",
      },
      {
        category: "vehicles",
        confidence: "low",
        details:
          "AB tarzı plakalar ve Dogu Avrupa arac karmasi tek basina yeterli olmasa da Kiril yaziyla birlikte dogru yone iter.",
        distinctiveness: 2,
        positionHint: "araclar",
        shortText: "AB plaka ve Kiril kombinasyonunu izle.",
        sortOrder: 40,
        tags: ["eu-plates", "cars"],
        timing: "revealed",
        title: "AB plaka + Kiril kombinasyonu",
      },
      {
        category: "environment",
        confidence: "low",
        details:
          "Kuru-kontinental isik ve merkez bulvar hissi tek basina belirleyici degil, ancak Kiril yazinin yaninda ikincil teyit olarak faydali.",
        distinctiveness: 1,
        positionHint: "genel isik ve cadde genisligi",
        shortText: "Kontinental sehir hissini yaziya ekle.",
        sortOrder: 50,
        tags: ["climate", "boulevard"],
        timing: "revealed",
        title: "Kontinental merkez hissi",
      },
    ],
    context: {
      countryCode: "BG",
      countryName: "Bulgaristan",
      locality: "Sofya",
      regionName: "Merkez cevresi",
    },
    difficulty: "hard",
    heading: 281,
    key: "sofia-center",
    label: "Sofya merkez doku",
    pitch: -1,
    position: { lat: 42.6979, lng: 23.3242 },
    status: "ready",
    summary:
      "Kiril yazisi ve Dogu Avrupa merkez doku karmasiyla ayristirilan bir Sofya kaydi.",
    tags: ["europe", "bulgaria", "urban", "script-heavy"],
    verificationNotes:
      "Starter kayit. Audit turlarinda tramvay ve tabela tipi daha kesinlestirilecek.",
    verificationState: "seeded",
    viewZoom: 1,
  },
  {
    clueSeed: [
      {
        category: "architecture",
        confidence: "high",
        details:
          "Reykjavik merkezinde renkli ya da mat metal kapli dusuk katli yapilar sahnenin en ayirici taraflarindan biridir. Cephe malzemesi bu kayitta kritik onemdedir.",
        distinctiveness: 5,
        positionHint: "bina cephe kaplamalari",
        shortText: "Metal kapli dusuk katli evlere bak.",
        sortOrder: 10,
        tags: ["metal-cladding", "houses"],
        timing: "revealed",
        title: "Metal kaplama konutlar",
      },
      {
        category: "vehicles",
        confidence: "medium",
        details:
          "Izlanda'da sari arka plaka cok guclu teyittir. Parkli araclar secilebiliyorsa plaka rengi hizli cevap verir.",
        distinctiveness: 4,
        positionHint: "park halindeki araclar",
        shortText: "Sari arka plaka gorunurse not et.",
        sortOrder: 20,
        tags: ["yellow-plates", "cars"],
        timing: "revealed",
        title: "Sari plaka teyidi",
      },
      {
        category: "environment",
        confidence: "medium",
        details:
          "Acik hava, azacik agac, genis gokyuzu ve kuzey Atlantik hissi Reykjavik icin guclu bir arka plan kurar.",
        distinctiveness: 3,
        positionHint: "genel ortam",
        shortText: "Agac azligi ve acik havayi not et.",
        sortOrder: 30,
        tags: ["subarctic", "open-sky"],
        timing: "playing",
        title: "Kuzey Atlantik ortam hissi",
      },
      {
        category: "road-layout",
        confidence: "medium",
        details:
          "Temiz ve sade yol boyasi, dusuk katli yapilarla birlestiginde Reykjavik merkezini diger Avrupa baskentlerinden ayirir.",
        distinctiveness: 2,
        positionHint: "yol boyasi",
        shortText: "Sade yol boyasini konut dokusuyla birlikte oku.",
        sortOrder: 40,
        tags: ["road-lines", "small-city"],
        timing: "playing",
        title: "Sade yol duzeni",
      },
      {
        category: "street-furniture",
        confidence: "low",
        details:
          "Direk, levha ve sokak ekipmani genelde temiz ve az yogundur. Bu sade ortam metal kapli evlerle birlikte Izlanda lehine calisir.",
        distinctiveness: 2,
        positionHint: "levha ve direkler",
        shortText: "Sade sokak ekipmanina dikkat et.",
        sortOrder: 50,
        tags: ["clean-streets", "signage"],
        timing: "revealed",
        title: "Sadelik etkisi",
      },
    ],
    context: {
      countryCode: "IS",
      countryName: "Izlanda",
      locality: "Reykjavik",
      regionName: "Midborg",
    },
    difficulty: "medium",
    heading: 318,
    key: "reykjavik-midborg",
    label: "Reykjavik merkez sokagi",
    pitch: -1,
    position: { lat: 64.1462, lng: -21.9425 },
    status: "ready",
    summary:
      "Metal kapli dusuk katli evler ve sari plaka teyidiyle okunacak bir Reykjavik merkez kaydi.",
    tags: ["iceland", "north-atlantic", "urban", "environment-heavy"],
    verificationNotes:
      "Starter kayit. Audit sonrasi reflektor, kaldirim ve cati detaylari daha spesifiklestirilebilir.",
    verificationState: "seeded",
    viewZoom: 1,
  },
];

export const curatedLocationSeed: GameLocationWithClues[] = curatedSeedInput.map((location) => {
  const locationId = `loc-${location.key}`;
  const slug = location.key;

  return {
    clues: location.clueSeed.map((clue, index) => ({
      ...clue,
      id: `clue-${location.key}-${index + 1}`,
      locationId,
    })),
    location: {
      context: location.context,
      difficulty: location.difficulty,
      heading: location.heading,
      id: locationId,
      label: location.label,
      pitch: location.pitch,
      position: location.position,
      slug,
      status: location.status,
      summary: location.summary,
      tags: location.tags,
      verificationNotes: location.verificationNotes,
      verificationState: location.verificationState,
      viewZoom: location.viewZoom,
    },
  };
});
